"""empty message

Revision ID: d902df8633e7
Revises: fcc39c31adce
Create Date: 2023-10-24 08:58:49.758892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd902df8633e7'
down_revision = 'fcc39c31adce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyrobek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=70), nullable=True),
    sa.Column('sn', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sklad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vyrobek_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('stav', sa.Enum('Nakup', 'Prodej'), nullable=False),
    sa.ForeignKeyConstraint(['vyrobek_id'], ['vyrobek.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sklad')
    op.drop_table('vyrobek')
    # ### end Alembic commands ###
